### ISSUE TITLE
DC-DP-QAM8 and DC-DP-QAM16

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis#7]
There is not a clear bibliography about the difference between these indicated modulation types and the usual DP-QAM8/16. 
The definition are inherited by other YANG module and we need to verify the real needs for these modulation types.

**Comment by italobusi** [comment]
These are few references I have found from Google:

https://www.ietf.org/proceedings/101/slides/slides-101-ccamp-sessa-10-signaling-extensions-for-media-channel-sub-carriers-in-sson-01

https://ieeexplore.ieee.org/document/8570782

https://ieeexplore.ieee.org/document/6985541

https://www.osapublishing.org/abstract.cfm?URI=OFC-2014-Th4F.3

**Comment by italobusi** [comment]
These identities have been defined in:

https://tools.ietf.org/html/draft-lee-ccamp-optical-impairment-topology-yang-00

**Comment by sergiobelotti** [comment]
@EstherLerouzic , @ggalimba56 : the two modulation format is already there in the YANG definition. Could you verify definitely if these definitions are real needed or if it is better to delete form the module?
That should be done in the view of update for IETF 115.

**Comment by ggalimba56** [comment]
I’m not sure what is the issue, the 16QAM, DP-16QAM and DC-DP-16QAM definitions are clear and these 3 modulation formats are different.  Then, probably the most common is the DP-16QAM but this doesn’t mean we can delete the other two.

**Comment by italobusi** [comment]
The YANG description does not provide a detailed technical definition of these modulation formats (besides the expansion of the acronym) nor a reference document where a reader can find a detailed definition

The 16QAM, DP-16QAM are quite clear to me since I know what they are

The DC-DP-16QAM is not fully clear to me

From the literature I have found (see https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/issues/7#issuecomment-701238678) it looks like that this modulation format produces a dual-carrier OTSi while our draft is assuming OTSis are only single-carrier

**Comment by sergiobelotti** [comment]
weekly call 06-06-23

The final decision was to remove all the modulation formats with DC- prefix .
